export const itsDepartments = [
  "Department of Physics",
  "Department of Mathematics",
  "Department of Statistics",
  "Department of Chemistry",
  "Department of Biology",
  "Department of Actuarial Science",
  "Department of Mechanical Engineering",
  "Department of Chemical Engineering",
  "Department of Engineering Physics",
  "Department of Industrial and Systems Engineering",
  "Department of Materials and Metallurgical Engineering",
  "Department of Food Engineering",
  "Department of Process Safety Engineering",
  "Department of Electrical Engineering",
  "Department of Biomedical Engineering",
  "Department of Computer Engineering",
  "Department of Informatics",
  "Department of Information Systems",
  "Department of Information Technology",
  "Department of Civil Engineering",
  "Department of Architecture",
  "Department of Environmental Engineering",
  "Department of Urban and Regional Planning",
  "Department of Geomatics Engineering",
  "Department of Geophysical Engineering",
  "Department of Naval Architecture and Shipbuilding",
  "Department of Marine Engineering",
  "Department of Ocean Engineering",
  "Department of Marine Transportation Engineering",
  "Department of Offshore Engineering",
  "Department of Industrial Design",
  "Department of Interior Design",
  "Department of Visual Communication Design",
  "Department of Business Management",
  "Department of Development Studies",
  "Department of Civil Infrastructure Engineering",
  "Department of Industrial Mechanical Engineering",
  "Department of Automation Electrical Engineering",
  "Department of Industrial Chemical Engineering",
  "Department of Instrumentation Engineering",
  "Department of Business Statistics",
  "Department of Medicine",
  "Department of Medical Technology",
  "School of Interdisciplinary Management and Technology (SIMT)"
];
